---
version: "2"
services:

  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # The domain name used to access Nextcloud. Ever used?
      - VIRTUAL_HOST=${NEXTCLOUD_VIRTUAL_HOST}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_VIRTUAL_HOST}
    volumes:
      - /portainer/Files/AppData/Config/Nextcloud/Config:/config
      - ${MOUNTED_DATA_PATH}/data:/data
      - ${MOUNTED_DATA_PATH}/apps:/var/html/www/nextcloud/apps
    ports:
      - ${PORT}:443
    restart: unless-stopped
    links:
      - maria_db
      - redis
      - collabora

  maria_db:
    image: linuxserver/mariadb
    container_name: maria_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${MOUNTED_DATABASE_PATH}:/config
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped

  collabora:
    image: collabora/code
    expose:
      - 9980
    #cap_add: # Apparently Collaboras documentation has at some point omitted this cap. Testing w/o
    #  - MKNOD
    environment:
      # Domain the service should be accessed from, e.g. cloud.example.com
      - domain=${NEXTCLOUD_VIRTUAL_HOST}
      - VIRTUAL_HOST=${COLLABORA_VIRTUAL_HOST}
      - DONT_GEN_SSL_CERT=YES
      - LETSENCRYPT_HOST=${COLLABORA_VIRTUAL_HOST}
      #- VIRTUAL_PORT=9980 # is default, leave for clarity
      # Extra parameters to Collabora, see also
      # https://www.collaboraoffice.com/code/nginx-reverse-proxy/
      # SSL terminates at the proxy
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    restart: unless-stopped
